# Generated by Django 5.1.1 on 2024-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
