# Generated by Django 5.1.1 on 2024-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=20)),
                ('session', models.CharField(help_text="Enter the section in the format 'YYYY/YYYY'", max_length=9)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
