# Generated by Django 5.1.1 on 2024-10-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_term_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
