# Generated by Django 5.1 on 2024-09-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacheradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheradmin',
            name='staff_id',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, unique=True),
        ),
    ]
