# Generated by Django 5.1 on 2024-09-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacheradmin', '0002_teacheradmin_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheradmin',
            name='token',
        ),
    ]
