# Generated by Django 5.1.1 on 2024-10-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_name', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('ONLINE', 'online'), ('CASH', 'cash'), ('POS', 'point of Sale')], max_length=20)),
                ('status', models.CharField(default='processing', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('OUTSTANDING', 'Outstanding'), ('NOT_PAID', 'Not paid')], default='NOT_PAID', max_length=30)),
                ('payment_id', models.CharField(max_length=30, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('POS', 'POS'), ('CASH', 'Cash'), ('TRANSFER', 'Transfer')], default='CASH', max_length=30)),
                ('payment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
