# Generated by Django 5.1 on 2024-08-31 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent.parent'),
            preserve_default=False,
        ),
    ]
