# Generated by Django 5.1.1 on 2024-10-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('student', '0002_delete_attendance'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('OUTSTANDING', 'Outstanding'), ('NOT_PAID', 'Not paid')], default='NOT_PAID', max_length=30)),
                ('payment_id', models.CharField(max_length=30, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('POS', 'POS'), ('CASH', 'Cash'), ('TRANSFER', 'Transfer')], default='CASH', max_length=30)),
                ('payment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
