# Generated by Django 5.1 on 2024-08-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_cost_paymenttype_amount_payment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='amount',
            new_name='cost',
        ),
    ]
