# Generated by Django 5.1.1 on 2024-10-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_physicalpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='name',
            new_name='payment_name',
        ),
    ]
