# Generated by Django 5.1 on 2024-08-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_amount_paymenttype_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ONLINE', 'online'), ('CASH', 'cash'), ('POS', 'point of Sale')], max_length=20),
        ),
    ]
