# Generated by Django 5.1 on 2024-09-11 03:36

import django.db.models.deletion
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('other_name', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('employment_type', models.CharField(choices=[('FULLTIME', 'Fulltime'), ('GRADUATE_ASSISTANT', 'Graduate Assistant'), ('PART_TIME', 'Part-time'), ('INTERN', 'Intern'), ('CORPER', 'Corper')], max_length=20)),
                ('home_address', models.CharField(max_length=55)),
                ('local_government_area', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=15)),
                ('nin', models.CharField(max_length=11, unique=True)),
                ('bvn', models.CharField(max_length=11, unique=True)),
                ('staff_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('NON_TEACHING', 'Non-teaching')], max_length=20)),
                ('staff_id', models.CharField(blank=True, default=staff.models.staff_registration_id, max_length=25, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='Staff_profile/')),
                ('img_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_period', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.accountinfo')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='staff.staff')),
            ],
            options={
                'ordering': ['-pay_period', 'staff__last_name'],
                'unique_together': {('staff', 'pay_period')},
            },
        ),
    ]
