# Generated by Django 5.1 on 2024-08-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyMaterial',
            new_name='SubjectMaterial',
        ),
    ]
