# Generated by Django 5.1 on 2024-09-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='subject_material',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='Subject_material/'),
        ),
    ]
