# Generated by Django 5.1 on 2024-09-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_remove_subjectmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='Subject_material/'),
        ),
    ]
