# Generated by Django 5.1 on 2024-09-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_alter_subjectmaterial_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmaterial',
            old_name='subject_material',
            new_name='material_url',
        ),
    ]
