# Generated by Django 5.1.1 on 2024-09-29 08:33

import django.db.models.deletion
import hostelmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('warden', models.ForeignKey(limit_choices_to={'staff_type': 'NON_TEACHING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=hostelmanagement.models.unique_room_id, max_length=10, unique=True)),
                ('max_occupants', models.PositiveIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostelmanagement.hostel')),
                ('occupants', models.ManyToManyField(blank=True, limit_choices_to={'type': 'BOARDER'}, to='student.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hostel', 'room_id'), name='unique_room_per_hostel')],
            },
        ),
    ]
