# Generated by Django 5.1.1 on 2024-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
