# Generated by Django 5.1 on 2024-09-01 04:22

import parent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='code',
            field=models.CharField(default=parent.models.parent_id, max_length=20, unique=True),
        ),
    ]
