# Generated by Django 5.1.1 on 2024-10-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dormitary', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(limit_choices_to={'staff_type': 'NON_TEACHING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Dormitary.hostel'),
        ),
    ]
