# Generated by Django 5.1 on 2024-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='Student_profile/'),
        ),
    ]
