# Generated by Django 5.1 on 2024-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_image',
            new_name='img_url',
        ),
    ]
