# Generated by Django 5.1 on 2024-08-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(max_length=15),
        ),
    ]
