# Generated by Django 5.1 on 2024-08-27 14:49

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='local_government_area',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(default=student.models.student_registration_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(max_length=20),
        ),
    ]
