# Generated by Django 5.1.1 on 2024-11-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asessment', '0001_initial'),
        ('grade', '0001_initial'),
        ('student', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='asessment.quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asessment.quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asessment.quizsession'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asessment.question'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asessment.option'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='asessment.quizsession'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asessment.studentresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together={('session', 'question', 'selected_option')},
        ),
    ]
