# Generated by Django 5.1.1 on 2024-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asessment', '0002_rename_question_question_text_remove_option_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
