# Generated by Django 5.1.1 on 2024-10-27 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(max_length=5, null=True)),
                ('color', models.CharField(blank=True, max_length=55, null=True)),
                ('sit_capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'staff_type': 'NON_TEACHING'}, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.bus')),
                ('students', models.ManyToManyField(related_name='commutes', to='student.student')),
            ],
            options={
                'unique_together': {('uuid', 'bus')},
            },
        ),
    ]
