# Generated by Django 5.1.1 on 2024-09-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentattendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
